import 'package:flutter/material.dart';

const Color mainDarkColor = Color(0xFF15BE77);
const Color mainLightColor = Color(0xFF53E88B);
const Color bgInputOrangeColor = Color(0xFFF9A84D);
const Color hintTextColor = Color(0xFFf4cbaf);
const Color hintTextInputColor = Color(0xFF3B3B3B);
const Color textBlackColor = Color(0xFF000000);
const Color textWhiteColor = Color(0xFFFFFFFF);
const Color textOrangeColor = Color(0xFFFF7C32);
const Color textDarkVioletColor = Color(0xFF6B3A5B);
const Color textGreyColor = Color(0xFF808080);
const Color bgWhiteColor = Color(0xFFFFFFFF);
const Color activeColor = Color(0xFF53E88B);
const Color orangeDarkColor = Color(0xFFDA6317);
const Color orangeLightColor = Color(0xFFfef6ed);
const Color greenWhiteLightColor = Color(0xFFEDFCF3);
const Color greenWhiteDarkColor = Color(0xFFCCF5DC);
const Color greyLightColor = Color(0xFFF6F6F6);
const Color greyDarktColor = Color(0xFFE4E4E4);
const Color redDarkColor = Color(0xFFCC3C3C);
const Color redLightColor = Color(0xFFFF4B4B);
const Color shadowColor = Color(0xFFF6F7FD);
const Color goldLightColor = Color(0xFFFFF7E8);
const Color goldDarkColor = Color(0xFFFEB12A);
